name: Deploy Dockerized Flask App - Docker Workshop

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: self-hosted

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Stop and remove Docker containers
      run: |
        docker-compose down


    - name: Run Docker Compose
      run: |
        docker-compose up -d
